"""empty message

Revision ID: 23b87bb820c1
Revises: 
Create Date: 2022-11-04 00:34:28.856758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b87bb820c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('placeId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('placeId')
    )
    op.create_table('statistics',
    sa.Column('statisticId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placeId', sa.Integer(), nullable=True),
    sa.Column('ocupability', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('statisticId')
    )
    op.create_table('user',
    sa.Column('userId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('statistics')
    op.drop_table('place')
    # ### end Alembic commands ###
