version: "3"
services:
    web:
        build: .
        ports:
            - "80:80"
        restart: always
        env_file:
            - .env
        volumes: 
            - .:/api
        depends_on: 
            - db
    db:
        image: postgres
        restart: always
        env_file: 
            - .env