name: ci

on:
  # Trigger the workflow on push or pull reques,
  # but only for the master branc
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: user/app:latest
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}